version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb+srv://tungproduct:tungproduct@cluster0.sfmmbem.mongodb.net/event_management?retryWrites=true&w=majority&appName=Cluster0
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./api/uploads:/app/uploads
      - ./api/.env:/app/.env
      - ./api/serviceAccountKey.json:/app/serviceAccountKey.json
    restart: unless-stopped
    networks:
      - event-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - event-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  mongo-data:
